services:
  - type: web
    name: dxfvec
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 dxfvec.web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
